config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/secret'
  devise_for :users
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#index"
  resources :events do
    resources :participations
    resources :charges, only: [:new, :create]
  end

  resources :users, only: [:index,:show] do
    resources :avatars, only: [:create]
  end

  resources :events, only: [:show] do
    resources :event_pictures, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  #validates :start_date, :title, :description, :price, :location, :duration, presence: true
  #validates :title, length: { minimum: 5, maximum: 140 }
  #validates :description, length: { minimum: 20, maximum: 1000 }
  #validates :price, length: { minimum: 1, maximum: 1000 }
  #validate :start_date_cannot_be_in_the_past
  #validate :duration_positive_and_multiple_of_five

  belongs_to :admin, class_name: "User", foreign_key: "user_id", dependent: :destroy
  has_many :participations
  has_one_attached :event_picture

  def duration_positive_and_multiple_of_five
    errors.add(:duration, "must be postive and multiple of 5") if
      !duration.positive? and (duration % 5 == 0)
  end

  #def start_date_cannot_be_in_the_past
  #  errors.add(:start_date, "can't be in the past") if
  #    !start_date.blank? and start_date < Date.today
  #end
  
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User", foreign_key: "user_id", dependent: :destroy
  #after_create :participation_send
  
  #def participation_send
  #  ParticipationMailer.participate_email(self.attendee, self).deliver_now
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #after_create :welcome_send
  has_many :participations
  has_many :events
  has_one_attached :avatar
  validates :email, presence: true,uniqueness: {case_sensitive: false},
  length: {minimum:3,maximum:25},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  #def welcome_send
  #  UserMailer.welcome_email(self).deliver_now
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
    
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
    redirect_to new_event_participation_path(params[:event_id])
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/event_pictures_controller.rb
class EventPicturesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.event_picture.attach(params[:event_picture])
    redirect_to(event_path(@event))
  end
end

app/controllers/events_controller.rb
require 'date'
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end


  def create
    @event = Event.new(event_params)
    @event.update(user_id: current_user.id )
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end  
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event = Event.find(11)
    @event.destroy
    redirect_to 'events'
  end


  private
  def event_params
    params.require(:event).permit(:start_date, :user_id, :duration, :title, :description)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to root
    end
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[ show edit update destroy ]
  require 'faker'
  # GET /participations or /participations.json
  def index
    @participations = Participation.all
  end

  # GET /participations/1 or /participations/1.json
  def show
  end

  # GET /participations/new
  def new
    @participation = Participation.new
  end

  # GET /participations/1/edit
  def edit
  end

  # POST /participations or /participations.json
  def create
    @participation = Participation.new(participation_params)
    @participation.update(user_id:current_user.id,event_id:params[:event_id])
    respond_to do |format|
      if @participation.save
        format.html { redirect_to '/events', notice: "Gossip was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
  

  # PATCH/PUT /participations/1 or /participations/1.json
  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to @participation, notice: "Participation was successfully updated." }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1 or /participations/1.json
  def destroy
    @participation.destroy
    respond_to do |format|
      format.html { redirect_to participations_url, notice: "Participation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participation
      @participation = Participation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def participation_params
      params.require(:participation).permit(:event_id,:stripe_customer_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]

  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  private
  
  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_picures_helper.rb
module EventPicuresHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/avatars/create.html.erb
<h1>Avatars#create</h1>
<p>Find me in app/views/avatars/create.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="500"
    data-locale="auto">
</script>
<% end %>

app/views/event_pictures/create.html.erb
<h1>EventPicures#create</h1>
<p>Find me in app/views/event_picures/create.html.erb</p>

app/views/events/_form.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Title of the document</title>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Teko:400,700" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="events.scss" rel="stylesheet">
</head>

<body>

<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<br><br>
  <div class="container contact-form">
            <div class="contact-image">
                <a href="https://ibb.co/n0prC6h"><img src="https://i.ibb.co/z5dsJQK/header-tours-evenements.jpg" alt="header-tours-evenements" border="0"></a>
            </div>
            <form method="post">
                <h3>New event</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Start Date *" value=""/>
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Duration *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtPhone" class="form-control" placeholder="Title*" value="" />
                        </div>
                        <div class="form-group">
                            <%= form.submit %>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Description *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>
<% end %>
</body>

</html>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
  <% @events.each do |event| %> 
    <div class="col-sm-6 card-deck">
    <div class="card mb-3" style="width: 20rem; text-align: center">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
          <h6 class="card-subtitle mb-2 text-muted">Admin :<%= User.find_by(id:event.user_id).first_name %></h6>
            <p class="card-text"><%= event.description %></p>
            <p class="card-text">Start Date : <%= event.start_date %></p>            
            <a href="<%= event_path(event.id) %>" class="card-link btn btn-dark">Show</a>
      </div>
    </div>
    </div>
  <% end %>   
  </div>
  logged in as <%=current_user.email if current_user%>
  <div class="left_a" style="margin-right:10px;">
  <a href="<%= new_event_path%>" class ="btn btn-light">Créer un Event</a>
  </div>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>ceci est la page show</h1>
<div class="jumbotron text-center bg-dark text-light">
  <h1>Titre: <%= @event.title %></h1>
  <p>Description: <%= @event.description %> </p>
  <p>nb d'inscrits: <%= Participation.where(event_id:@event.id).length %> </p>
  <p>Contact Orga: <%= User.find_by(id: @event.user_id).email %></p> 
  <a class="btn btn-primary" href="<%=events_path%>" >Back</a>
  <a href="<%= user_path(@event.user_id) %>" class="card-link btn btn-dark">Admin Profile</a>
  <a class="btn btn-primary" href="/events/<%= @event.id %>/participations">Participations</a>
</div>

<% if !(Participation.where(event_id:@event.id).map{|u| u.user_id}.include?(current_user.id)) && !(@event.user_id == current_user.id) %>  
  <a href="<%= new_event_charge_path(@event.id) %>" class="card-link btn btn-dark">Inscription</a>
<% end %>

<% if @event.user_id == current_user.id %>  
  <a href="<%=  event_participations_path(params[:id]) %>" class="card-link btn btn-dark">Mon Espace Evenement</a>
<% end %>

<p>Bienvenue sur la page d'ajout d'un event_picture pour le User portant l'id : <%=@event.id%></p>
<h3>Image actuel</h3>
<%if @event.event_picture.attached?%>
  <%= image_tag @event.event_picture, alt: 'event_picture' %>
<%else%>
  <p>=== Il n'y a pas encore d'event_picture lié à cet utilisateur ===</p>
<%end%>

<% if @event.user_id == current_user.id %>
  <h3>Changer d'event_picture ?</h3>
  <%= form_tag event_event_pictures_path(@event), multipart: true do %>
    <%= file_field_tag :event_picture %>
    <%= submit_tag "mettre à jour" %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark fixed-bottom">
 <div class="text-center p-1">
    © 2020 Copyright:
    <a href="https://google.com/">hugoboss.com</a>
  </div>  
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The Eventbrite Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
      <a class="nav-link" href="<%=events_path%>">Accueil</a>           
        </li>
        <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%=user_path(current_user)%>">Détails profil</a>              
                <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE" >Disconnect</a></p>   
          </div>
          <%end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap.min', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'layouts/navigation' %>      

    <%= yield %>
    
    <%= render 'layouts/footer' %>      

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
  <html>
    <head></head>
    <body>
      <%= yield %>
    </body>
  </html>

app/views/layouts/nevbis.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The Eventbrite Project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
<a class="nav-link" href="<%=events_path%>">Accueil <span class="sr-only">(current)</span></a>            <span class="visually-hidden">(current)</span>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="<%= new_event_path %>">Add Event</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item dropdown">
          <% if user_signed_in? %>
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%=user_path(current_user)%>">Détails profil</a>              
                <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-confirm="Êtes-vous sûr ?" data-method="DELETE" >Disconnect</a></p>   
          </div>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-sm-2" type="text" placeholder="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/participations/_form.html.erb
<%= form_with(model: participation) do |form| %>
  <% if participation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
        <% participation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :stripe_customer_id %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<h1>Editing Participation</h1>

<%= render 'form', participation: @participation %>

<%= link_to 'Show', @participation %> |
<%= link_to 'Back', participations_path %>

app/views/participations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<% @participations.each do |participation| %>
  <% if Participation.where(event_id:params[:event_id]).include?(participation)%>
    <%= User.find_by(id:participation.user_id).email %>
    <br>
  <% end %>
<%end%>

<% if Event.find(params[:event_id]).user_id == current_user.id %>
  <a href="<%= edit_event_path(params[:event_id])%>" class="card-link btn btn-dark" >Edit Event</a>
  <br><br>
  <a href="/events/<%=params[:id]%>" class="btn btn-danger" data-confirm="Êtes-vous sûr ?" data-method="DELETE">Cancel Event</a>
<%end%>

app/views/participations/new.html.erb
<h1>Thank you for you inscription <%= current_user.email%> </h1>
<h1>New participation</h1>

<%= form_for @participation, url: {action: "create"} do |f| %>
 
  <div class="form_group">
    <%= f.label :stripe_customer_id %>
    <%= f.text_field :stripe_customer_id %>
  </div>
  <div class="form_group">
    <%= f.submit "Create" %>
  </div>
<% end %>


<%= link_to 'Main Page', events_path %>

app/views/participations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= User.find_by(id:@participation.user_id).email %>
</p>

<%= link_to 'Edit', edit_event_participation_path(@participation) %> |
<%= link_to 'Back', event_participations_path(@participation) %>

app/views/static_pages/index.html.erb
<div class="page-content">
<div class="container" id="home-container">
  <div class="jumbotron text-center text-white">
    <h1 class="display-4">Eventbrite Project</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-outline-success btn-lg" href="<%= user_session_path %>" role="button">Sign In!</a>
  </div>
</div>
</div>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/index.html.erb
<h1>ceci est la page d'accueil user</h1>

<% @users.each do |user| %> 
  <%= user.first_name %>
  <a href="<%= user_path(user.id) %>" class="card-link btn btn-dark">Show</a>
  <br>
<% end %>   

app/views/users/show.html.erb
<div class="container mb-5 mt-2">
  <div class="row justify-content-center text-center mt-2">
  <h1>User Profile</h1>
    <div class="m-5">
    <p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@user.id%></p>
    <h3>Avatar actuel</h3>
    <%if @user.avatar.attached?%>
        <%= image_tag @user.avatar, alt: 'avatar' %>
    <%else%>
      <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
    <%end%>
    </div>
    <div class="container mt-5">
<% if @user == current_user %>
  <a href="<%= edit_user_registration_path %>" class="card-link btn btn-dark">Edit Email/password</a>
<% end %>
  <% if @user == current_user %>
    <h3>Changer d'avatar ?</h3>
    <%= form_tag user_avatars_path(@user), multipart: true do %>
      <%= file_field_tag :avatar %>
      <%= submit_tag "mettre à jour" %>
    <% end %>
  <% end %>
</div>
</div>
  
</div>